### ISSUE TITLE
Spiders crash the game when touching Mexicraft's nopal

### ISSUE THREAD

**Issue by HauntedSniper** [TheCyberBrick/Spiders-2.0#17]
**I was in the desert at night fighting an enderman when the game crashed, this is what the crash log said. I guess Mexicraft is not a very important mod, so I don't expect specific mod compatibility if it isn't possible, since it is an Mcreator mod, but maybe there're some problems with Spiders detecting damage or hitboxes that could be solved and would help compatibility.**

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 10/7/20 3:51 PM
Description: Colliding entity with block

java.lang.NullPointerException: Colliding entity with block
	at tcb.spiderstpo.common.entity.mob.BetterSpiderEntity.func_213295_a(BetterSpiderEntity.java:159) ~[?:1.0.1] {re:classloading}
	at net.mcreator.mexicraft.procedures.NopalDamageProcedure.executeProcedure(NopalDamageProcedure.java:23) ~[?:?] {re:classloading}
	at net.mcreator.mexicraft.block.NopalBottomBlock$BlockCustomFlower.func_196262_a(NopalBottomBlock.java:220) ~[?:?] {re:classloading}
	at net.minecraft.block.BlockState.func_196950_a(BlockState.java:386) ~[?:?] {re:classloading,xf:OptiFine:default,re:mixin}
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:815) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:shetiphiancore:Entity.getOnPosition,xf:fml:quark:generic-update-hook,xf:fml:shetiphiancore:Entity.createRunningParticles,xf:fml:quark:override-collision,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.Entity.func_213315_a(Entity.java:560) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:shetiphiancore:Entity.getOnPosition,xf:fml:quark:generic-update-hook,xf:fml:shetiphiancore:Entity.createRunningParticles,xf:fml:quark:override-collision,re:mixin,pl:accesstransformer:B}
	at tcb.spiderstpo.common.entity.mob.AbstractClimberEntity.func_213315_a(AbstractClimberEntity.java:721) ~[?:1.0.1] {re:classloading}
	at tcb.spiderstpo.common.entity.mob.AbstractClimberEntity.travelOnGround(AbstractClimberEntity.java:680) ~[?:1.0.1] {re:classloading}
	at tcb.spiderstpo.common.entity.mob.AbstractClimberEntity.func_213352_e(AbstractClimberEntity.java:530) ~[?:1.0.1] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2289) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:charm:LivingEntity,xf:fml:apotheosis:apothpotiondmg,xf:fml:shetiphiancore:LivingEntity.playFallSound,xf:fml:apotheosis:apothshieldblock,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:649) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:mixins.optiforge.json:net.minecraft.entity.MixinMobEntity,pl:mixin:A}
	at tcb.spiderstpo.common.entity.mob.BetterSpiderEntity.func_70636_d(BetterSpiderEntity.java:81) ~[?:1.0.1] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:charm:LivingEntity,xf:fml:apotheosis:apothpotiondmg,xf:fml:shetiphiancore:LivingEntity.playFallSound,xf:fml:apotheosis:apothshieldblock,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:397) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:mixins.optiforge.json:net.minecraft.entity.MixinMobEntity,pl:mixin:A}
	at tcb.spiderstpo.common.entity.mob.AbstractClimberEntity.func_70071_h_(AbstractClimberEntity.java:333) ~[?:1.0.1] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600) ~[?:?] {re:classloading,xf:fml:quark:add-rave-hook,xf:fml:quark:change-sleeping-player-count,re:mixin}
	at net.minecraft.world.server.ServerWorld$$Lambda$16504/271019573.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:536) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401) ~[?:?] {re:classloading,xf:fml:quark:add-rave-hook,xf:fml:quark:change-sleeping-player-count,re:mixin}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:163) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at tcb.spiderstpo.common.entity.mob.BetterSpiderEntity.func_213295_a(BetterSpiderEntity.java:159)
	at net.mcreator.mexicraft.procedures.NopalDamageProcedure.executeProcedure(NopalDamageProcedure.java:23)
	at net.mcreator.mexicraft.block.NopalBottomBlock$BlockCustomFlower.func_196262_a(NopalBottomBlock.java:220)
	at net.minecraft.block.BlockState.func_196950_a(BlockState.java:386)

-- Block being collided with --
Details:
	Block: Block{mexicraft:nopalbottom}[age=0]
	Block location: World: (-3885,65,237), Chunk: (at 3,4,13 in -243,14; contains blocks -3888,0,224 to -3873,255,239), Region: (-8,0; contains chunks -256,0 to -225,31, blocks -4096,0,0 to -3585,255,511)
Stacktrace:
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:815)

-- Entity being checked for collision --
Details:
	Entity Type: spiderstpo:better_spider (tcb.spiderstpo.common.entity.mob.BetterSpiderEntity)
	Entity ID: 193
	Entity Name: Spider
	Entity's Exact location: -3885.37, 65.15, 236.95
	Entity's Block location: World: (-3886,65,236), Chunk: (at 2,4,12 in -243,14; contains blocks -3888,0,224 to -3873,255,239), Region: (-8,0; contains chunks -256,0 to -225,31, blocks -4096,0,0 to -3585,255,511)
	Entity's Momentum: 0.36, 0.31, 1.17
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.Entity.func_213315_a(Entity.java:560)
	at tcb.spiderstpo.common.entity.mob.AbstractClimberEntity.func_213315_a(AbstractClimberEntity.java:721)
	at tcb.spiderstpo.common.entity.mob.AbstractClimberEntity.travelOnGround(AbstractClimberEntity.java:680)
	at tcb.spiderstpo.common.entity.mob.AbstractClimberEntity.func_213352_e(AbstractClimberEntity.java:530)
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2289)
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:649)
	at tcb.spiderstpo.common.entity.mob.BetterSpiderEntity.func_70636_d(BetterSpiderEntity.java:81)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:397)
	at tcb.spiderstpo.common.entity.mob.AbstractClimberEntity.func_70071_h_(AbstractClimberEntity.java:333)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600)
	at net.minecraft.world.server.ServerWorld$$Lambda$16504/271019573.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: spiderstpo:better_spider (tcb.spiderstpo.common.entity.mob.BetterSpiderEntity)
	Entity ID: 193
	Entity Name: Spider
	Entity's Exact location: -3885.37, 65.15, 236.95
	Entity's Block location: World: (-3886,65,236), Chunk: (at 2,4,12 in -243,14; contains blocks -3888,0,224 to -3873,255,239), Region: (-8,0; contains chunks -256,0 to -225,31, blocks -4096,0,0 to -3585,255,511)
	Entity's Momentum: 0.36, 0.31, 1.17
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:536)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['RipHSniper'/153, l='Tlatpantepek', x=-3887.56, y=65.00, z=234.51]]
	Chunk stats: ServerChunkCache: 5043
	Level dimension: DimensionType{minecraft:overworld}
	Level name: Tlatpantepek
	Level seed: -8238176625155565171
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (16,77,48), Chunk: (at 0,4,0 in 1,3; contains blocks 16,0,48 to 31,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1445488 game time, 2394094 day time
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 83928 (now: false), thunder time: 45826 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:163)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2212205568 bytes (2109 MB) / 9663676416 bytes (9216 MB) up to 9663676416 bytes (9216 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx9G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre30.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.31.jar fml TRANSFORMATIONSERVICE 
		/OptiForge-MC1.15.2-0.1.27.jar FakeOptiFine TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/OptiForge-MC1.15.2-0.1.27.jar optiforge TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.31
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinfml@1.5.2
	Mod List: 
		vanillaextension-1.15.2-1.0.3.jar Vanilla Extension {vanillaextension@1.15.2-1.0.3 DONE}
		Craft_and_Hunt_V1.1.0_MC_1.15.2.jar Craft and Hunt {craftandhunt@0.9 DONE}
		roughmobsrevamped-1.15.2-4.1.2.jar Rough Mobs Revamped {roughmobsrevamped@version DONE}
		berry_good-2.0.0.jar Berry Good {berry_good@2.0 DONE}
		ElenaiDodge-1.15.2-1.7.0.jar Elenai Dodge {elenaidodge@1.15.2-1.7.0 DONE}
		spiders-2.0-1.15.2-1.0.1.jar Spiders 2.0 {spiderstpo@1.0.1 DONE}
		Mexicraft+1.0.1.jar Mexicraft {mexicraft@1.0.1 DONE}
		jei-1.15.2-6.0.2.12.jar Just Enough Items {jei@6.0.2.12 DONE}
		OptiForge-MC1.15.2-0.1.27.jar OptiForge {optiforge@0.1.27 DONE}
		DoggyTalents-1.15.2-1.15.2.3 (1).jar Doggy Talents {doggytalents@1.15.2.3 DONE}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
		Bamboo-Blocks-1.15.2-1.4.1.jar Bamboo Blocks {bambooblocks@NONE DONE}
		Buzzier-Bees-1.15.2-1.5.2.jar Buzzier Bees {buzzierbees@1.5.2 DONE}
		ProjectE-1.15.2-PE1.0.4.jar ProjectE {projecte@1.0.4 DONE}
		Mekanism-1.15.2-9.10.9.422.jar Mekanism {mekanism@9.10.9 DONE}
		flower-breeding-1.15.2-1.4.jar Lizzie's Flower Breeding {acmc@1.0 DONE}
		deadlyendphantoms-1.15.2-1.01.jar Deadly End Phantoms {deadlyendphantoms@1.01 DONE}
		Upgrade-Aquatic-1.15.2-1.7.1.jar Upgrade Aquatic {upgrade_aquatic@1.7.1 DONE}
		SneakyMagic-v2.0-1.15.2.jar Sneaky Magic {sneakymagic@2.0 DONE}
		BetterCaves-1.15.2-1.0.jar YUNG's Better Caves {bettercaves@1.15.2-1.0 DONE}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 DONE}
		WallpaperCraft-1.15.2-1.2.4.jar Wallpapercraft {wallpapercraft@1.2.4 DONE}
		WallpapercraftSlabs-1.15.2-1.1.0.jar Wallpapercraft - Slabs! {wallpapercraftslabs@1.1.0 DONE}
		TerraForged-1.15.2-0.1.2.jar TerraForged {terraforged@0.1.2 DONE}
		WallpapercraftStairs-1.15.2-1.1.1.jar Wallpapercraft - Stairs {wallpapercraftstairs@1.1.1 DONE}
		EnameledArmor-1.15.1-1.0.0.5.jar Enameled Armor Mod {ea@1.0.0.5 DONE}
		CookingForBlockheads_1.15.2-8.0.3.jar Cooking for Blockheads {cookingforblockheads@8.0.3 DONE}
		sweetconcrete-1.15.2-1.7.1.jar Sweet Concrete {sweetconcrete@1.15.2-1.7.1 DONE}
		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 DONE}
		citadel-1.1.11.jar Citadel {citadel@1.1.11 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		MutantBeasts-1.15.2-1.0.7.jar Mutant Beasts {mutantbeasts@1.15.2-1.0.7 DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		Reliquary-1.15.2-1.3.4.995.jar Reliquary {xreliquary@1.15.2-1.3.4.995 DONE}
		snowundertrees-1.15.2-v1.1.1.jar Snow Under Trees {snowundertrees@v1.1.1 DONE}
		EnhancedVanilla_Snapshot_20w27a-Forge-1.15.2.31.2.0.jar Enhanced Vanilla {enhancedvanilla@Snapshot 20w27a DONE}
		buildinggadgets-3.4.0.jar Building Gadgets {buildinggadgets@3.4.0 DONE}
		Apotheosis-1.15.2-3.3.5.jar Apotheosis {apotheosis@3.3.5 DONE}
		ProgressiveBosses-2.1.5-mc1.15.2 (1).jar Progressive Bosses {progressivebosses@2.1.5-mc1.15.2 DONE}
		mcw-doors-1.0.0-mc1.15.2 (1).jar Macaw's Doors {mcwdoors@1.0.0 DONE}
		additional_lights-1.15.2-2.0.2.jar Additional Lights {additional_lights@2.0.2 DONE}
		iceandfire-2.0.3-1.15.2.jar Ice and Fire {iceandfire@2.0.3-1.15.2 DONE}
		MekanismGenerators-1.15.2-9.10.9.422.jar Mekanism: Generators {mekanismgenerators@9.10.9 DONE}
		SnowRealMagic-1.15.2-1.7.5 (1).jar Snow! Real Magic! {snowrealmagic@1.7.5 DONE}
		Kiwi-1.15.2-2.7.1.jar Kiwi {kiwi@2.7.1 DONE}
		JEITweaker-1.15.2-1.0.1.3.jar JEI Tweaker {jeitweaker@1.0.1.3 DONE}
		Swamp-Expansion-1.15.2-1.7.3.jar Swamp Expansion {swampexpansion@NONE DONE}
		beyond_the_nether_wastes_v_1.1.0.jar Beyond The Nether Wastes {btnw@1.0.0 DONE}
		forge-1.15.2-31.2.31-universal.jar Forge {forge@31.2.31 DONE}
		shetiphiancore-1.15-3.7.2.jar ShetiPhian-Core {shetiphiancore@3.7.2 DONE}
		Bones-1.15.2-1.3.2.jar Bones {bones@1.15.2-1.3.2 DONE}
		refinedstorage-1.8.8.jar Refined Storage {refinedstorage@1.8.8 DONE}
		corpse-1.15.2-1.0.6.jar Corpse {corpse@1.15.2-1.0.6 DONE}
		RottenCreatures-1.15.2-0.9.7.jar Rotten Creatures {rotten_creatures@0.9.7 DONE}
		forge-1.15.2-31.2.31-client.jar Minecraft {minecraft@1.15.2 DONE}
		cofh_core-1.15.2-0.6.4b.jar CoFH Core {cofh_core@0.6.4b DONE}
		ensorcellation-1.15.2-0.6.0b.jar Ensorcellation {ensorcellation@0.6.0b DONE}
		The-Endergetic-Expansion-1.15.2-v1.3.2.jar The Endergetic Expansion {endergetic@1.3.2 DONE}
		repurposedstructures-1.15.2-1.7.2.jar Repurposed Structures {repurposed_structures@1.15.2-1.7.2 DONE}
		AmbientSounds_v3.0.20_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		GentleFawn-1.1.1-MC1.15.2.jar Gentle Fawn {gentlefawn@1.1.1 DONE}
		BiomesOPlenty-1.15.2-10.0.0.366-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.366 DONE}
		BetterDrowning-1.15.2-1.0.3.jar BetterDrowning {betterdrowning@1.0.3 DONE}
		packedup-1.0.18-mc1.15.jar PackedUp {packedup@1.0.18 DONE}
		masonry-1.15.2-0.3.4 (1).jar Masonry {masonry@NONE DONE}
		archers_paradox-1.15.2-0.6.0b.jar Archer's Paradox {archers_paradox@0.6.0b DONE}
		simplefarming-1.15.2-1.3.0.jar Simple Farming {simplefarming@1.15.1-1.3.0 DONE}
		xercamod-1.15.2-2.6.jar Xerca Mod {xercamod@1.15.2-2.6 DONE}
		Bountiful-1.15.2-3.1.2.jar Bountiful {bountiful@1.15.2-3.1.2 DONE}
		goprone-1.15.x-1.3.0.jar GoProne {goprone@1.15.x-1.3.0 DONE}
		curios-FORGE-1.15.2-2.0.2.4.jar Curios API {curios@FORGE-1.15.2-2.0.2.4 DONE}
		Savage-and-Ravage-1.15.2-1.1.4.jar Savage & Ravage {savageandravage@1.1.4 DONE}
		extlights-2.1.jar Extended Lights {extlights@2.1 DONE}
		autumnity-1.3.3-1.15.2.jar Autumnity {autumnity@1.3.3 DONE}
		polymorph-FORGE-1.15.2-0.10.jar Polymorph {polymorph@FORGE-1.15.2-0.10 DONE}
		multibeds-1.15-1.6.1.jar Multi-Beds {multibeds@1.6.1 DONE}
		horse_colors-1.15.2-1.4.0.1.jar Realistic Horse Genetics {horse_colors@1.15.2-1.4.0.1 DONE}
		AutoRegLib-1.5-40 (1).jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 DONE}
		Enhanced-Mushrooms-1.15.2-v1.2.2.jar Enhanced Mushrooms {enhanced_mushrooms@$1.1.0 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		Mushroom+Quest_1.15.2_v2.3.jar Mushroom Quest {mushroomquest@1.0.0 DONE}
		EndReborn+[0.6.1].jar End: Reborn {endreborn@0.6.1 DONE}
		lottaterracotta-1.15.2-1.3.1.jar Lotta Terracotta {lottaterracotta@1.15.2-1.3.1 DONE}
		lanterncolors-1.15.2-1.0.1.jar Lantern Colors {lanterncolors@1.15.2-1.0.1 DONE}
		TaigaAdditions+[0.1.2].jar Taiga Additions {taigaexpansion@0.1.2 DONE}
		furniture-7.0.0-pre16-1.15.1 (1).jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		mobcatcher-2.2 (1).jar Mob Catcher {mobcatcher@2.2 DONE}
		productivebees-1.15.2-0.3.2.jar Productive Bees {productivebees@1.15.2-0.3.2 DONE}
		+skeleton-expansion-3.0.1_1.15.2.jar Skeleton Expansion+ {skeleton_expansion@1.0.0 DONE}
		ilikewood-1.15.2-2.2.2.0 (2).jar I Like Wood {ilikewood@1.15.2-2.2.2.0 DONE}
		Aquaculture-1.15.2-2.0.20.jar Aquaculture 2 {aquaculture@1.15.2-2.0.20 DONE}
		Charm-1.15.2-1.5.9.jar Charm {charm@1.15.2-1.5.9 DONE}
		Strange-1.15.2-1.0.0-beta.5.hotfix1.jar Strange {strange@1.15.2-1.0.0-beta.5 DONE}
		Charmonium-1.15.2-1.0.1.jar Charmonium {charmonium@1.15.2-1.0.1 DONE}
		BetterMineshaftsForge-1.15.2-1.3.1.jar YUNG's Better Mineshafts {bettermineshafts@1.15.2-1.3.1 DONE}
		ExtendedNetherBackport-1.15.2-Beta-4.1.2.jar Extended Nether Backport {extendednether@4.1.2 DONE}
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data
		snowrealmagic:snowrealmagic
	Player Count: 1 / 8; [ServerPlayerEntity['RipHSniper'/153, l='Tlatpantepek', x=-3887.56, y=65.00, z=234.51]]
	Data Packs: mod:spiderstpo (incompatible), mod:extlights, mod:wallpapercraftslabs (incompatible), mod:wallpapercraftstairs (incompatible), mod:deadlyendphantoms, mod:bones (incompatible), mod:gentlefawn, vanilla, mod:vanillaextension, mod:craftandhunt (incompatible), mod:roughmobsrevamped (incompatible), mod:berry_good (incompatible), mod:elenaidodge, mod:mexicraft, mod:jei (incompatible), mod:optiforge, mod:doggytalents (incompatible), mod:abnormals_core, mod:bambooblocks (incompatible), mod:buzzierbees, mod:projecte, mod:mekanism, mod:acmc (incompatible), mod:upgrade_aquatic (incompatible), mod:sneakymagic, mod:bettercaves (incompatible), mod:waystones (incompatible), mod:wallpapercraft, mod:terraforged, mod:ea, mod:cookingforblockheads (incompatible), mod:sweetconcrete (incompatible), mod:placebo (incompatible), mod:citadel (incompatible), mod:naturescompass (incompatible), mod:mutantbeasts (incompatible), mod:bookshelf (incompatible), mod:xreliquary (incompatible), mod:snowundertrees (incompatible), mod:enhancedvanilla, mod:buildinggadgets (incompatible), mod:apotheosis (incompatible), mod:progressivebosses, mod:mcwdoors, mod:additional_lights (incompatible), mod:iceandfire, mod:mekanismgenerators, mod:snowrealmagic, mod:kiwi, mod:jeitweaker, mod:swampexpansion (incompatible), mod:btnw, mod:forge (incompatible), mod:shetiphiancore (incompatible), mod:refinedstorage (incompatible), mod:corpse, mod:rotten_creatures, mod:cofh_core (incompatible), mod:ensorcellation (incompatible), mod:endergetic (incompatible), mod:repurposed_structures, mod:ambientsounds (incompatible), mod:biomesoplenty, mod:betterdrowning (incompatible), mod:packedup, mod:masonry, mod:archers_paradox (incompatible), mod:simplefarming, mod:xercamod (incompatible), mod:bountiful (incompatible), mod:goprone, mod:curios (incompatible), mod:savageandravage, mod:autumnity, mod:polymorph, mod:multibeds (incompatible), mod:horse_colors, mod:autoreglib (incompatible), mod:quark, mod:enhanced_mushrooms, mod:oreexcavation (incompatible), mod:mushroomquest, mod:endreborn (incompatible), mod:lottaterracotta (incompatible), mod:lanterncolors, mod:taigaexpansion, mod:cfm (incompatible), mod:mobcatcher (incompatible), mod:productivebees, mod:skeleton_expansion, mod:ilikewood, mod:aquaculture, mod:charm (incompatible), mod:strange (incompatible), mod:charmonium (incompatible), mod:bettermineshafts (incompatible), mod:extendednether (incompatible), file/Repurposed_Structures-Swamp_Expansion.zip, file/coordinates hud v1.1.1.zip (incompatible), file/custom nether portals v1.1.1.zip, file/ilikewood-1.15.2-2.2.2.0-biomesoplenty-datapack.zip, file/player head drops v1.0.0.zip (incompatible), file/terracotta rotation wrench v1.0.1.zip (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre30
	OptiFine Build: 20200622-083032
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13559 Compatibility Profile Context 26.20.12028.2
	OpenGlRenderer: Radeon RX 580 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 6

**Hope anything can be done.**

**Comment by TheCyberBrick** [comment]
This problem is caused by Mexicraft's code, please report it to them. Thanks
