### ISSUE TITLE
The game crashed whilst ticking entity

### ISSUE THREAD

**Issue by lookatmypie** [TheCyberBrick/Spiders-2.0#28]
Error: java.lang.IllegalStateException: Tag spiderstpo:non_climbable used before it was bound
Exit Code: -1

Latest version, 1.16.4, latest forge

**Comment by lookatmypie** [comment]
`java.lang.IllegalStateException: Tag spiderstpo:non_climbable used before it was bound
	at net.minecraft.tags.TagRegistry$NamedTag.func_232944_c_(TagRegistry.java:131) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.tags.TagRegistry$NamedTag.func_230235_a_(TagRegistry.java:142) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.block.Block.func_203417_a(Block.java:115) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.monster.SpiderEntity.canClimbOnBlock(SpiderEntity.java:1784) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:spiderstpo.mixins.json:ClimberEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:BetterSpiderEntityMixin,pl:mixin:A}
	at net.minecraft.entity.monster.SpiderEntity$$Lambda$5392/426839001.test(Unknown Source) ~[?:?] {}
	at net.minecraft.util.math.shapes.VoxelShapeSpliterator.func_234878_a_(SourceFile:86) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.util.math.shapes.VoxelShapeSpliterator.tryAdvance(SourceFile:62) ~[?:?] {re:mixin,re:classloading}
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51] {}
	at net.minecraft.entity.monster.SpiderEntity.forEachCollisonBox(SpiderEntity.java:1120) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:spiderstpo.mixins.json:ClimberEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:BetterSpiderEntityMixin,pl:mixin:A}
	at net.minecraft.entity.monster.SpiderEntity.getCollisionBoxes(SpiderEntity.java:1125) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:spiderstpo.mixins.json:ClimberEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:BetterSpiderEntityMixin,pl:mixin:A}
	at net.minecraft.entity.monster.SpiderEntity.updateWalkingSide(SpiderEntity.java:862) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:spiderstpo.mixins.json:ClimberEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:BetterSpiderEntityMixin,pl:mixin:A}
	at net.minecraft.entity.monster.SpiderEntity.onLivingTick(SpiderEntity.java:1021) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:spiderstpo.mixins.json:ClimberEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:BetterSpiderEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.handler$zch000$onLivingTick(MobEntity.java:1487) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:spiderstpo.mixins.json:MobEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:spiderstpo.mixins.json:MobEntityMixin,pl:mixin:A}
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:43) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityClientMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:spiderstpo.mixins.json:MobEntityMixin,pl:mixin:A}
	at net.minecraft.entity.monster.SpiderEntity.func_70071_h_(SpiderEntity.java:78) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:spiderstpo.mixins.json:ClimberEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:BetterSpiderEntityMixin,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:192) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld$$Lambda$5380/628859285.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:161) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1483) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.0.2.jar:35.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$470/1693003105.call(Unknown Source) [forge-1.16.4-35.0.2.jar:35.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}`

**Comment by lookatmypie** [comment]
`-- Entity being ticked --
Details:
	Entity Type: minecraft:spider (net.minecraft.entity.monster.SpiderEntity)
	Entity ID: 126
	Entity Name: Spider
	Entity's Exact location: 115.13, 50.00, -14.85
	Entity's Block location: World: (115,50,-15), Chunk: (at 3,3,1 in 7,-1; contains blocks 112,0,-16 to 127,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:161) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}

`

**Comment by TheCyberBrick** [comment]
Could you please upload the entire log to something like [https://gist.github.com/](https://gist.github.com/)?
Are you using other mods and/or modifying [Tags](https://minecraft.gamepedia.com/Tag) or the mod file? This error shouldn't happen unless something removed the "spiderstpo:non_climbable" tag.
