### ISSUE TITLE
Incompatible with Performant

### ISSUE THREAD

**Issue by Camawama** [TheCyberBrick/Spiders-2.0#37]
While using Performant and Spiders 2.0, spiders will get stuck on walls and never move up them.

**Comment by TheCyberBrick** [comment]
This problem is known, but I haven't found a simple way to make it compatible yet.

**Comment by BGB-Rex** [comment]
hey, I'd just like to say that I think I found a temporary fix. Thanks to the user "AtheoAng3l0_New" that mentioned turning off some AI tweaks in the Perforrmants configs so I did some testing and found out that changing these specific ones makes the spiders work as intended

["Entity settings"]

fastCollisions = false
fastPathFinding = false
multiEntities = false

["Entity AI Settings"]

goalselectorrate = 1

Hope this helps someone

**Comment by Camawama** [comment]
> hey, I'd just like to say that I think I found a temporary fix. Thanks to the user "AtheoAng3l0_New" that mentioned turning off some AI tweaks in the Perforrmants configs so I did some testing and found out that changing these specific ones makes the spiders work as intended
> 
> ["Entity settings"]
> 
> fastCollisions = false
> fastPathFinding = false
> multiEntities = false
> 
> ["Entity AI Settings"]
> 
> goalselectorrate = 1
> 
> Hope this helps someone

You are amazing, thank you

**Comment by ekiplier** [comment]
I know it's been a while, but there's a blacklist option in the performant config so you don't actually need to turn off these features for every mob, just for spiders.

**Comment by TigerWalts** [comment]
I believe that this incompatibility is also causing a crash on dedicated servers. The client is probably catching the exception and avoiding a crash. Currently experienced on Better Minecraft v24. Making the above changes stopped the crashes.

- Crash Report - https://gist.github.com/TigerWalts/1d50c78c75531f6b3ca52ce0a2ee7965

```
java.lang.NullPointerException: Ticking entity
	at tcb.spiderstpo.common.entity.movement.AdvancedWalkNodeProcessor.getDirectionalPathNodeType(AdvancedWalkNodeProcessor.java:953) ~[spiderstpo:1.0.4] {re:classloading}
	at tcb.spiderstpo.common.entity.movement.AdvancedWalkNodeProcessor.getDirectionalPathNodeType(AdvancedWalkNodeProcessor.java:935) ~[spiderstpo:1.0.4] {re:classloading}
	at tcb.spiderstpo.common.entity.movement.AdvancedWalkNodeProcessor.func_186330_a(AdvancedWalkNodeProcessor.java:931) ~[spiderstpo:1.0.4] {re:classloading}
	at tcb.spiderstpo.common.entity.movement.ClimberMoveController.isWalkableAtOffset(ClimberMoveController.java:276) ~[spiderstpo:1.0.4] {re:mixin,re:classloading}
	at tcb.spiderstpo.common.entity.movement.ClimberMoveController.func_75641_c(ClimberMoveController.java:68) ~[spiderstpo:1.0.4] {re:mixin,re:classloading}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:692) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:spiderstpo.mixins.json:MobEntityMixin,pl:mixin:APP:environmental.mixins.json:MobEntityMixin,pl:mixin:APP:buzzier_bees.mixins.json:MobEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.MobEntityAccessor,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	...
```

**Comment by NIKITAzed** [comment]
just had that same issue on a dedicated Better Minecraft V24 server and Melih in the luna pixel discord pointed me here, worked like a charm
